services:
  - type: web
    name: coffeeconnect
    runtime: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
databases:
  - name: coffeeconnect-db
    plan: free
    databaseName: coffeeconnect
    user: coffeeconnect
