spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
  thymeleaf:
    cache: true

server:
  port: ${PORT:8080}

app:
  frontend-url: https://coffeeconnect.onrender.com
