package com.coffeeconnect.enums;

public enum AdminActionType {
    USER_DELETED, USER_SUSPENDED, USER_ACTIVATED, VERIFICATION_APPROVED,
    VERIFICATION_REJECTED, COMPANY_ADDED, COMPANY_EDITED, COMPANY_DELETED,
    OFFICE_ADDED, OFFICE_EDITED, OFFICE_DELETED, REQUEST_CANCELLED,
    CONNECTION_REMOVED, REPORT_DISMISSED, USER_WARNED, USER_BANNED,
    PASSWORD_RESET, SETTINGS_UPDATED, NOTIFICATION_SENT, MESSAGE_DELETED,
    LOGIN_FAILED, ACCOUNT_LOCKED
}
